version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./tours.json:/docker-entrypoint-initdb.d/tours.json:ro
      - ./movies.json:/docker-entrypoint-initdb.d/movies.json:ro
      - ./people.json:/docker-entrypoint-initdb.d/people.json:ro
volumes:
  mongodb_data:

