apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  # annotations:
    # kubernetes.io/ingress.global-static-ip-name: 35.207.116.26
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: jenkins
          servicePort: 8080
      # - path: /moreinfo/*
      #   backend:
      #     serviceName: http-svc
      #     servicePort: 80