apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMTGRFYk12SnoyazJnQ20reTVsClFxcVpBSlpFWWtLcHRiekJLUkZhNlJYeHViWW0zeDEwdWlYRWNVK21EdTF4TDBMQjhUWjZ2eWN3b21yMm96QXUKcWt0bXNGcTNlL0hvam44OWZHdG0rQVRUSkdOQVgwMTNFQ0U2Ukgwc1NhZC9LVzMzZnBpYUdiUjFtdUtBNlVCZwpCQUNmdEY2RmxzN0xpcDFpcnAzTG9yVU5Fd0piUWR0WHBXZ2RZVUM4ZVlWQk1TTWhUQUdrZlk4QzFldjM0bUJxCm9zWEVham9MaE9nZzNkcVdtK0dHMjZQTFJhcUc5MmZzLzZiQ2hUcmRPTlhlcUM0c1RnZzdJZkJVQ3liYzhwOWIKSjJFQ2JwVlg1WnpMYWVPbHdZbzJkOHlKWFlsRlYxK2Y3Yy9zYm1rOU5GZ1lHZW16QUlHTVc1dWxNajZCYnF5aApOS1VDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNOL1ArWFI2SlVKUUM1czJtajhQTkRzWm93CnI4SVBOQTBZOTd1NlFBbnBHQjNpYWx2L0pyeFROM0xrZGs0QVBLQnkveGtyVUN2a1dPdXZlWjYwSndEb2MyN3EKT0xTWlBySUdyK2x5c0Mwa3BYTDZDRFR2VWtoRFdPc0NSZWIwVFhkTzFxWi9hRWNHRlRqQVc1Q1h0eG45SkRpdwpSZHZqVlZuMUVoYk56YzY4M0daYnJKd2hxTnZMSzlLVUV2YTB0eERxeUdJU3BEM2kzT2pHWWdXWWRlcFNxNFhHCjAzcHNjUUdkZEd1QXdQNmZNNEpzcERyNFl2VUtMenJqWDkyeGx5YkZlcXliTDI5elkwc3hNbzFucElhbEJXOFAKYzVyNlAva2dydXhMcStlRWE1VStyc3V0THF1R2VIWnJuNXZMMmN0cEdoZnhYL1ZxR28xc1RhTDltelk0Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - client auth